#!/system/bin/sh

(
if grep jamiethemorris /proc/version > /dev/null
then
   echo "** jamiethemorris's boot configuration:"
   echo "** disabling mpdecision **"
   if [ -r /system/bin/mpdecision ]; then
       mount -o remount,rw /system
       mv /system/bin/mpdecision /system/bin/mpdecision.jamiethemorris
       mount -o remount,ro /system
   fi
   stop mpdecision
   for script in /system/etc/jamiethemorris/*
   do
	$script
   done
else
   echo "!! jamiethemorris's boot configuration not running, this isn't my kernel !!"
   echo "** enabling mpdecision"
   if [ -r /system/bin/mpdecision.jamiethemoris ]; then
       mount -o remount,rw /system
       mv /system/bin/mpdecision.jamiethemorris /system/bin/mpdecision
       mount -o remount,ro /system
   fi
   start mpdecision
fi
)2>&1 | tee /sdcard/jamiethemorris.log
