#!/system/bin/sh

(
if grep jamiethemorris /proc/version > /dev/null
then
   echo "** jamiethemorris's boot configuration:"
   
   for script in /system/etc/jamiethemorris/*
   do
	$script
   done
else
   echo "!! jamiethemorris's boot configuration not running, this isn't my kernel !!"
   
fi
)2>&1 | tee /sdcard/jamiethemorris.log
